### ISSUE TITLE
How to exclude a certain folder?

### ISSUE THREAD

**Issue by hammi1** [google/adb-sync#25] opened 2018-04-01 11:02 UTC
Is there a way to exclude certain folders from being transferred, in either a forward or reverse sync?

For e.g., my main conundrum is that I want to sync my phones /sdcard/ folder onto my backup drive, which would add all new pictures/videos and downloads. However, I want to exclude the /sdcard/Android/ folder which has unnecessary cache files.

Is there a way to do this, or would it be better for me to sync only the most needed folders (such as DCIM, Downloads, etc)?

Thank you

**Comment by spewnm** [comment] 2018-04-14 03:38
Since the feature request still hasn't been taken and whatnot, you can do something like a shell loop through [extended globbing](https://www.linuxjournal.com/content/bash-extended-globbing).
```bash
for directory in !(UnwantedPattern); do
    adb-sync "$directory" /storage/5111-3BEE
done
```
This can help for forward syncs, but I don't think there's a very easy workaround for directories on your Android phone itself.

**Comment by divVerent** [comment] 2018-11-27 21:00
Duplicate of #21.

**Closed by divVerent** 2018-11-27 21:00 UTC

**Comment by DoctorSubtilis** [comment] 2019-05-20 15:11
Hi, @https://github.com/skewerr I tried your code
    for directory in "!(-*)"; do
        adb-sync /home/schede/cultura/inglese/. sdcard/Documents/inglese/
    done
But I'm not able to sinc my folder with the tablet. I have to sync all except symlinks (folders and files). Can you help me?

**Comment by DoctorSubtilis** [comment] 2019-05-20 15:13
Hi, @https://github.com/skewerr I tried your code  

    for directory in "!(-*)"; do
      adb-sync /home/schede/cultura/inglese/. sdcard/Documents/inglese/
    done  

But I'm not able to sinc my folder with the tablet. I have to sync all except symlinks (folders and files). Can you help me?
